// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Setting: typeof import('./src/components/Setting/Setting.vue')['default']
    SettingHeader: typeof import('./src/components/Setting/SettingHeader.vue')['default']
    System: typeof import('./src/components/System/System.vue')['default']
    SystemHeader: typeof import('./src/components/System/SystemHeader.vue')['default']
  }
}

export { }
